### ISSUE TITLE
enable recaptcha/akismet

### ISSUE THREAD

**Issue by VincentTam** [rbind/data-blog#327]
due to spam

**Comment by matdoering** [comment]
Hey Vincent,
Yup, I've been noticing the spam. It's quite bothersome. I've disabled commenting until I find the time to implement protective measures. Do you know whether there's a tutorial out there to integrate captchas into static sites or with staticman? Cheers!

**Comment by VincentTam** [comment]
Staticman has reCAPTCHA support, but it only works for v2.  To integrate this to a site, some tempate code config like https://github.com/MunifTanjim/minimo/pull/224 is needed.

Great idea!  That would filter out the spam from GitHub.  I haven't heard of this feature on GitHub though.  Given the scale of GitHub API, I think implementing it inside the Node.JS app would be more feasible.  Spam filtering itself is an interesting application of data science.  Hope I can find a way to implement the anti-spam logic on the API side.

**Comment by matdoering** [comment]
Thanks for the advice! I'll take a look.

Yup, sounds fun, right? I guess there should be some freely available spam prediction models - I'm not sure though if their performance would be sufficient to integrate them into an automated system. Sounds like a research project :-D
